name: Open and update release Pull Requests
on:
  push:
    branches:
      - next

jobs:
  release:
    name: release
    if: github.repository == 'dgellow/openai-node'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dgellow/trigger-release-please@sam/test-release-please-fork
        id: release
        with:
          repo: dgellow/openai-node
          branch-with-changes: next
          stainless-api-key: ${{ secrets.STAINLESS_API_KEY }}

